// client/src/components/Avatar.tsx
interface Props {
  name: string;
  color: string;
  size?: 'normal' | 'small';
  online?: boolean;
}

export default function Avatar({ name, color, size = 'normal', online }: Props) {
  const initials = name
    .split(' ')
    .map(w => w[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);

  return (
    <div className={`avatar ${size}`} style={{ backgroundColor: color }}>
      {initials}
      {online && <div className="online-dot" />}
    </div>
  );
}

// client/src/components/Avatar.vue
<script setup lang="ts">
import { computed } from "vue";
const props = withDefaults(
  defineProps<{
    name: string;
    color: string;
    size?: "normal" | "small";
    online?: boolean;
  }>(),
  { size: "normal", online: false },
);
const initials = computed(() =>
  props.name
    .split(" ")
    .map((word) => word[0])
    .join("")
    .toUpperCase()
    .slice(0, 2),
);
</script>
<template>
  <div class="avatar" :class="size" :style="{ backgroundColor: color }">
    {{ initials }}
    <div v-if="online" class="online-dot" />
  </div>
</template>
