// client/src/components/NewChatModal.vue
<script setup lang="ts">
import { ref } from 'vue';
import { X } from 'lucide-vue-next';
import { api } from '../api';
import type { User } from '../types';
import { useI18n } from '../i18n';
import Avatar from './Avatar.vue';
const props = defineProps<{ type: 'direct' | 'group' }>();
const emit = defineEmits<{ close: []; created: [conversation: { id: string }] }>();
const { t } = useI18n();
const search = ref(''), results = ref<User[]>([]), selected = ref<User[]>([]), groupName = ref(''), loading = ref(false);
let searchTimer: ReturnType<typeof setTimeout> | undefined;
function searchUsers(value: string) {
  search.value = value; clearTimeout(searchTimer);
  searchTimer = setTimeout(async () => { if (!value.trim()) { results.value = []; return; } try { results.value = await api.searchUsers(value); } catch { results.value = []; } }, 180);
}
async function choose(user: User) {
  if (props.type === 'group') { selected.value = selected.value.some(item => item.id === user.id) ? selected.value.filter(item => item.id !== user.id) : [...selected.value, user]; return; }
  loading.value = true; try { emit('created', await api.createConversation('direct', [user.id])); } finally { loading.value = false; }
}
async function createGroup() {
  if (!selected.value.length || !groupName.value.trim()) return;
  loading.value = true; try { emit('created', await api.createConversation('group', selected.value.map(member => member.id), groupName.value)); } finally { loading.value = false; }
}
</script>
<template>
  <div class="modal-overlay" @click="emit('close')"><div class="modal" @click.stop>
    <div class="modal-header"><h3>{{ type === 'direct' ? t('newChat') : t('newGroup') }}</h3><button class="icon-btn" @click="emit('close')"><X :size="20" /></button></div>
    <div class="modal-body">
      <div v-if="type === 'group'" class="group-form"><input v-model="groupName" class="modal-search" :placeholder="t('groupName')"><div v-if="selected.length" class="selected-members"><div v-for="member in selected" :key="member.id" class="member-chip">{{ member.displayName }}<button @click="choose(member)">×</button></div></div></div>
      <input class="modal-search" :placeholder="t('searchUsers')" :value="search" autofocus @input="searchUsers(($event.target as HTMLInputElement).value)">
      <div v-for="user in results" :key="user.id" class="user-result" @click="choose(user)"><Avatar :name="user.displayName" :color="user.avatarColor" size="small"/><div class="user-result-info"><h4>{{ user.displayName }}</h4><p>@{{ user.username }}</p></div><span v-if="type === 'group' && selected.some(member => member.id === user.id)" class="user-result-check">✓</span></div>
      <button v-if="type === 'group'" class="create-group-btn" :disabled="loading || !selected.length || !groupName.trim()" @click="createGroup">{{ t('createGroup', { count: selected.length }) }}</button>
    </div>
  </div></div>
</template>

// client/src/components/NewChatModal.tsx
import { useState } from 'react';
import { X } from 'lucide-react';
import { api } from '../api';
import type { User } from '../types';
import { useI18n } from '../i18n';
import Avatar from './Avatar';

interface Props {
  type: 'direct' | 'group';
  onClose: () => void;
  onCreated: (conv: { id: string }) => void;
}

export default function NewChatModal({ type, onClose, onCreated }: Props) {
  const { t } = useI18n();
  const [search, setSearch] = useState('');
  const [results, setResults] = useState<User[]>([]);
  const [selectedMembers, setSelectedMembers] = useState<User[]>([]);
  const [groupName, setGroupName] = useState('');
  const [loading, setLoading] = useState(false);

  async function handleSearch(q: string) {
    setSearch(q);
    if (q.length < 1) { setResults([]); return; }
    try {
      const users = await api.searchUsers(q);
      setResults(users);
    } catch { /* ignore */ }
  }

  async function startDirectChat(userId: string) {
    setLoading(true);
    try {
      const conv = await api.createConversation('direct', [userId]);
      onCreated(conv);
    } catch { /* ignore */ }
    setLoading(false);
  }

  async function createGroup() {
    if (selectedMembers.length === 0 || !groupName.trim()) return;
    setLoading(true);
    try {
      const conv = await api.createConversation('group', selectedMembers.map(m => m.id), groupName);
      onCreated(conv);
    } catch { /* ignore */ }
    setLoading(false);
  }

  function toggleMember(user: User) {
    setSelectedMembers(prev =>
      prev.some(m => m.id === user.id)
        ? prev.filter(m => m.id !== user.id)
        : [...prev, user]
    );
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <h3>{type === 'direct' ? t('newChat') : t('newGroup')}</h3>
          <button className="icon-btn" onClick={onClose}>
            <X size={20} />
          </button>
        </div>
        <div className="modal-body">
          {type === 'group' && (
            <div className="group-form">
              <input
                className="modal-search"
                placeholder={t('groupName')}
                value={groupName}
                onChange={e => setGroupName(e.target.value)}
              />
              {selectedMembers.length > 0 && (
                <div className="selected-members">
                  {selectedMembers.map(m => (
                    <div key={m.id} className="member-chip">
                      {m.displayName}
                      <button onClick={() => toggleMember(m)}>&times;</button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          <input
            className="modal-search"
            placeholder={t('searchUsers')}
            value={search}
            onChange={e => handleSearch(e.target.value)}
            autoFocus
          />

          {results.map(user => (
            <div
              key={user.id}
              className="user-result"
              onClick={() => type === 'direct' ? startDirectChat(user.id) : toggleMember(user)}
            >
              <Avatar name={user.displayName} color={user.avatarColor} size="small" />
              <div className="user-result-info">
                <h4>{user.displayName}</h4>
                <p>@{user.username}</p>
              </div>
              {type === 'group' && selectedMembers.some(m => m.id === user.id) && (
                <span style={{ marginLeft: 'auto', color: 'var(--text-accent)' }}>✓</span>
              )}
            </div>
          ))}

          {type === 'group' && (
            <button
              className="create-group-btn"
              onClick={createGroup}
              disabled={loading || selectedMembers.length === 0 || !groupName.trim()}
            >
              {t('createGroup', { count: selectedMembers.length })}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
